name: No-Duplications

on: [push, pull_request]

jobs:
  nodup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: sudo npm install -g jscpd

    - name: No-Duplications beyond 3 lines
      run: jscpd . --min-lines 3 --min-tokens 48 --threshold 0
